// <auto-generated />
using System;
using AIManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921085738_AddChannelsAndDeliveryMode")]
    partial class AddChannelsAndDeliveryMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIManager.Api.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AnthropicApiKey")
                        .HasColumnType("text");

                    b.Property<string>("AnthropicBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("AnthropicMaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("AnthropicModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("JiraApiToken")
                        .HasColumnType("text");

                    b.Property<string>("JiraUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("JiraUser")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("TeamsPowerAutomateDmUrl")
                        .HasColumnType("text");

                    b.Property<string>("TeamsReportRecipient")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AIManager.Api.Domain.ChaseEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveredTo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RuleId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MemberId");

                    b.HasIndex("RuleId", "TargetDate");

                    b.ToTable("ChaseEvents");
                });

            modelBuilder.Entity("AIManager.Api.Domain.ChaseRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("integer");

                    b.Property<int?>("DestinationChannelId")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TestRecipientOverride")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<double?>("ThresholdHours")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationChannelId");

                    b.HasIndex("TeamId");

                    b.ToTable("ChaseRules");
                });

            modelBuilder.Entity("AIManager.Api.Domain.TaskUpdateFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignee")
                        .HasColumnType("text");

                    b.Property<string>("AssigneeEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasEstimate")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRemaining")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWorkDone")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Missing")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Verdict")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TargetDate", "IssueKey");

                    b.ToTable("TaskUpdateFindings");
                });

            modelBuilder.Entity("AIManager.Api.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AIManager.Api.Domain.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("JiraAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("AIManager.Api.Domain.TeamsChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("TeamsChannels");
                });

            modelBuilder.Entity("AIManager.Api.Domain.ChaseEvent", b =>
                {
                    b.HasOne("AIManager.Api.Domain.TeamMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIManager.Api.Domain.ChaseRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("AIManager.Api.Domain.ChaseRule", b =>
                {
                    b.HasOne("AIManager.Api.Domain.TeamsChannel", "DestinationChannel")
                        .WithMany()
                        .HasForeignKey("DestinationChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIManager.Api.Domain.Team", "Team")
                        .WithMany("Rules")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationChannel");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AIManager.Api.Domain.TeamMember", b =>
                {
                    b.HasOne("AIManager.Api.Domain.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AIManager.Api.Domain.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
